### ISSUE TITLE
Дублирование элементов пакета на странице пакета

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/os-hub-frontend#5]
![image](https://user-images.githubusercontent.com/2920817/42727398-8e22cadc-87ae-11e8-94e8-f50d07368b2b.png)

**Comment by artbear** [comment]
Даже еще хуже - дублирование есть и в общем списке пакетов

![image](https://user-images.githubusercontent.com/2920817/42727413-c7056a9e-87ae-11e8-9b7c-3bd5ee8645df.png)

**Comment by EvilBeaver** [comment]
we're workin' on it

Хотелось накрутить количество пакетов в хабе, но стало заметно... Чорт...
