### ISSUE TITLE
Битая кодировка на зеркале http://hub.oscript.ru

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/os-hub-frontend#8]
![image](https://user-images.githubusercontent.com/32082417/47756956-d3974200-dcef-11e8-8d69-b09ac48e1f19.png)

**Comment by EvilBeaver** [comment]
@dmpas, нужна помощь с зеркалом? Оно на чем там вращается, что кодировки поехали вдруг?

**Comment by dmpas** [comment]
кодировка в заголовке идёт, заголовки не зеркалятся. то есть, толк только от хранилища пакетов, сайт надо вообще грохнуть.
